search_params:
  area: 1
  employment: 'full'
  excluded_text: ''
  experience: 'doesNotMatter'
  hhtmFrom: 'vacancy_search_list'
  items_on_page: 20
  no_magic: 'true'
  order_by: 'publication_time'
  page: 0
  schedule: ''
  search_field: 'name'
  text: 'DevOps'
  n_pages: 5
  user: 'WOWEN'  

data:
  db_path: 'data/HH_vacancy.db'
  
reporting:
  report_updates: False
  user_chat_id: ''